{ config, lib, pkgs, self, syncdPkg, bootPkg, ... }:
{
  imports = [
    ../../profiles/linux-dev/default.nix
    # Generated by scripts/enroll.sh via `nixos-generate-config`.
    # Device-specific — gitignored, never committed.
    # Run `scripts/enroll.sh` before the first `nixos-rebuild switch`.
    ./hardware-configuration.nix
  ];

  networking.hostName = "builder-aarch64";

  sourceos.build = {
    role = "builder-aarch64";
    channel = "dev";
  };

  # Apple Silicon hardware support (module wired in via flake.nix
  # nixosConfigurations.builder-aarch64 modules list).
  hardware.asahi = {
    enable = true;
    setupAsahiSound = true;
    experimentalGpuAcceleration = true;
  };

  # Boot via systemd-boot: Asahi installer places m1n1 + U-Boot which
  # expose an EFI stub. NixOS picks it up via systemd-boot.
  # canTouchEfiVariables = false is mandatory — modifying EFI vars on
  # Apple Silicon can prevent booting macOS.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;

  # Flakes required for sourceos-syncd and prophet CLI
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Trusted substituters for the SourceOS binary cache (populated by Katello
  # after the content view is published)
  nix.settings.trusted-substituters = [
    "https://cache.nixos.org"
    "http://127.0.0.1:8101"
  ];
  nix.settings.trusted-public-keys = [
    "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
  ];

  users.users.sourceos = {
    isNormalUser = true;
    extraGroups = [ "wheel" "video" "audio" "networkmanager" "docker" ];
    # Set password post-install via `passwd sourceos` — never commit credentials
  };

  security.sudo.wheelNeedsPassword = false;

  # ── Docker (for Foreman+Katello local stack) ─────────────────────────────────
  # Foreman+Katello RPM packages have no aarch64 build for Fedora 40, so we run
  # the all-in-one container as linux/amd64 via qemu-user-static emulation.
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  boot.binfmt.emulatedSystems = [ "x86_64-linux" ];

  # ── Enrollment tooling ────────────────────────────────────────────────────────
  # age, sops, minisign, docker-compose, and hammer are required by scripts/enroll.sh
  environment.systemPackages = with pkgs; [
    age
    sops
    minisign
    docker-compose
    # hammer (Foreman CLI) — build from nixpkgs or use the rubygem directly
    ruby
    git
    curl
    jq
  ];

  # ── SOPS secrets ────────────────────────────────────────────────────────────
  # secrets.yaml is stored at /etc/sourceos/secrets.yaml (NOT in the repo).
  # Generated and encrypted by scripts/enroll.sh using the device age key.
  # Device-specific — each enrolled M2 has its own age key + encrypted secrets.
  sops.age.keyFile = "/etc/sourceos/age.key";
  sops.secrets.katello-password = {
    sopsFile = "/etc/sourceos/secrets.yaml";
    owner = "sourceos-syncd";
    group = "sourceos-syncd";
    mode = "0400";
  };

  # ── sourceos-syncd daemon ────────────────────────────────────────────────────
  # Polls local Katello every 5 min; applies new stable content view versions.
  # Password loaded via SOPS-managed secret (not committed to repo).
  sourceos.syncd = {
    enable = true;
    package = syncdPkg;
    sourceosBoot.package = bootPkg;
    katelloUrl = "https://127.0.0.1:8443";
    lifecycleEnv = "stable";
    locus = "local";
    flakeRef = "github:SociOS-Linux/source-os#builder-aarch64";
    pollInterval = 300;
    noVerifySsl = true;
    katelloPasswordFile = config.sops.secrets.katello-password.path;
    # signingPublicKey: set after generating the minisign key pair.
    # Generate: minisign -G -p /etc/sourceos/nix-cache.pub -s /run/secrets/nix-cache.key
    # Then embed the public key string here.
    healthCheck = {
      enable = true;
      delayAfterBootSec = 120;
      rollbackOnFailure = true;
    };
  };

  system.stateVersion = "25.05";
}
