{ config, lib, pkgs, self, syncdPkg, bootPkg, ... }:
{
  imports = [
    ../../profiles/linux-dev/default.nix
    # Generated by scripts/enroll.sh via `nixos-generate-config`.
    # Device-specific — gitignored, never committed.
    # Error if missing: run `sudo bash scripts/enroll.sh` from the repo root.
    ./hardware-configuration.nix
  ]
  # Device-specific settings written by scripts/enroll.sh:
  # signingPublicKey, harmonia trusted-public-key.
  # Optional: system builds safely without it (signing disabled).
  ++ lib.optional (builtins.pathExists ./enroll.nix) ./enroll.nix;

  networking.hostName = "builder-aarch64";

  sourceos.build = {
    role = "builder-aarch64";
    channel = "dev";
  };

  # Apple Silicon hardware support (module wired in via flake.nix
  # nixosConfigurations.builder-aarch64 modules list).
  hardware.asahi = {
    enable = true;
    setupAsahiSound = true;
    experimentalGpuAcceleration = true;
  };

  # Boot via systemd-boot: Asahi installer places m1n1 + U-Boot which
  # expose an EFI stub. NixOS picks it up via systemd-boot.
  # canTouchEfiVariables = false is MANDATORY on Apple Silicon.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # cache.nixos.org plus the local harmonia cache.
  # The harmonia signing key is added via enroll.nix after enrollment.
  nix.settings.trusted-substituters = [
    "https://cache.nixos.org"
    "http://127.0.0.1:8101"
  ];
  nix.settings.trusted-public-keys = [
    "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    # device-specific harmonia key appended by enroll.nix
  ];

  users.users.sourceos = {
    isNormalUser = true;
    extraGroups = [ "wheel" "video" "audio" "networkmanager" "docker" ];
  };

  security.sudo.wheelNeedsPassword = false;

  # ── Docker (for Foreman+Katello local stack) ────────────────────────────────
  # Katello RPMs have no aarch64 build for Fedora 40; run the container as
  # linux/amd64 via qemu-user-static emulation (same as Rosetta on macOS).
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  boot.binfmt.emulatedSystems = [ "x86_64-linux" ];

  # ── Local Nix binary cache (harmonia) ──────────────────────────────────────
  # Serves /nix/store as a binary cache on 127.0.0.1:8099.
  # nginx on :8101 wraps it and also serves nix-cache-info.minisig for
  # sourceos-syncd's signature verification step.
  services.harmonia = {
    enable = true;
    # Key generated by enroll.sh: nix-store --generate-binary-cache-key
    # Absent until enrollment; harmonia starts without signing (unsigned cache).
    signKeyPaths = lib.optional (builtins.pathExists "/etc/sourceos/harmonia-signing.key")
      "/etc/sourceos/harmonia-signing.key";
    settings.bind = "127.0.0.1:8099";
  };

  services.nginx = {
    enable = true;
    recommendedProxySettings = true;
    virtualHosts."nix-cache-local" = {
      listen = [{ addr = "127.0.0.1"; port = 8101; ssl = false; }];
      # Serve the minisig for sourceos-syncd signature verification.
      # The file is written by enroll.sh alongside harmonia key generation.
      locations."= /nix-cache-info.minisig" = {
        alias = "/etc/sourceos/nix-cache-info.minisig";
        extraConfig = ''
          default_type text/plain;
          add_header Cache-Control "no-cache";
        '';
      };
      # Proxy everything else to harmonia.
      locations."/" = {
        proxyPass = "http://127.0.0.1:8099";
        extraConfig = ''
          proxy_read_timeout 300;
        '';
      };
    };
  };

  # Allow nginx to read /etc/sourceos/nix-cache-info.minisig
  systemd.services.nginx.serviceConfig.ReadOnlyPaths = [ "/etc/sourceos" ];

  # ── Enrollment tooling ──────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [
    age
    sops
    minisign
    docker-compose
    ruby          # for hammer CLI gems
    git
    curl
    jq
    # nix-store --generate-binary-cache-key is part of the nix package (already present)
  ];

  # ── SOPS secrets ────────────────────────────────────────────────────────────
  # Stored at /etc/sourceos/secrets.yaml (NOT in the repo).
  # Generated and SOPS-encrypted by enroll.sh using the device age key.
  sops.age.keyFile = "/etc/sourceos/age.key";
  sops.secrets.katello-password = {
    sopsFile = "/etc/sourceos/secrets.yaml";
    owner = "sourceos-syncd";
    group = "sourceos-syncd";
    mode = "0400";
  };

  # ── sourceos-syncd daemon ────────────────────────────────────────────────────
  sourceos.syncd = {
    enable = true;
    package = syncdPkg;
    sourceosBoot.package = bootPkg;
    katelloUrl = "https://127.0.0.1:8443";
    lifecycleEnv = "stable";
    locus = "local";
    flakeRef = "github:SociOS-Linux/source-os#builder-aarch64";
    pollInterval = 300;
    noVerifySsl = true;
    katelloPasswordFile = config.sops.secrets.katello-password.path;
    # signingPublicKey is set via enroll.nix after minisign key generation.
    healthCheck = {
      enable = true;
      delayAfterBootSec = 120;
      rollbackOnFailure = true;
    };
  };

  system.stateVersion = "25.05";
}
