{ config, lib, pkgs, self, syncdPkg, bootPkg, ... }:
{
  imports = [
    ../../profiles/linux-dev/default.nix
    # Device-specific hardware config generated by scripts/enroll.sh.
    # Falls back to a CI-safe stub when not present on the current machine.
    (if builtins.pathExists ./hardware-configuration.nix
     then ./hardware-configuration.nix
     else ./hardware-configuration-stub.nix)
  ]
  # Device-specific settings written by scripts/enroll.sh:
  # signingPublicKey, harmonia trusted-public-key.
  # Optional: system builds safely without it (signing disabled).
  ++ lib.optional (builtins.pathExists ./enroll.nix) ./enroll.nix;

  networking.hostName = "builder-aarch64";

  sourceos.build = {
    role = "builder-aarch64";
    channel = "dev";
  };

  # Apple Silicon hardware support (module wired in via flake.nix
  # nixosConfigurations.builder-aarch64 modules list).
  hardware.asahi = {
    enable = true;
    setupAsahiSound = true;
  };

  # Boot via systemd-boot: Asahi installer places m1n1 + U-Boot which
  # expose an EFI stub. NixOS picks it up via systemd-boot.
  # canTouchEfiVariables = false is MANDATORY on Apple Silicon.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # cache.nixos.org, nixos-apple-silicon pre-built kernels, local harmonia.
  # The harmonia signing key is added via enroll.nix after enrollment.
  nix.settings.extra-substituters = [
    "https://cache.nixos.org"
    "https://nixos-apple-silicon.cachix.org"
    "http://127.0.0.1:8101"
  ];
  nix.settings.trusted-substituters = [
    "https://cache.nixos.org"
    "https://nixos-apple-silicon.cachix.org"
    "http://127.0.0.1:8101"
  ];
  nix.settings.trusted-public-keys = [
    "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    "nixos-apple-silicon.cachix.org-1:8psDu5SA5dAD7qA0zMy5UT292TxeEPzIz8VVEr2Js20="
    # device-specific harmonia key appended by enroll.nix
  ];

  users.users.sourceos = {
    isNormalUser = true;
    extraGroups = [ "wheel" "video" "audio" "networkmanager" "docker" ];
  };

  security.sudo.wheelNeedsPassword = false;

  # ── Docker (for Foreman+Katello local stack) ────────────────────────────────
  # Katello RPMs have no aarch64 build for Fedora 40; run the container as
  # linux/amd64 via qemu-user-static emulation (same as Rosetta on macOS).
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  boot.binfmt.emulatedSystems = [ "x86_64-linux" ];

  # ── Local Nix binary cache (harmonia) ──────────────────────────────────────
  # Serves /nix/store as a binary cache on 127.0.0.1:8099.
  # nginx on :8101 wraps it and also serves nix-cache-info.minisig for
  # sourceos-syncd's signature verification step.
  services.harmonia.cache = {
    enable = true;
    # Generated by enroll.sh step 7: nix-store --generate-binary-cache-key
    # The systemd ConditionPathExists below prevents harmonia from starting until
    # the key exists, so the service is safely inert before enrollment.
    signKeyPaths = [ "/etc/sourceos/harmonia-signing.key" ];
    settings.bind = "127.0.0.1:8099";
  };
  # Don't start harmonia until enrollment has generated the signing key.
  # After enroll.sh: `systemctl start harmonia` or next reboot.
  systemd.services.harmonia.unitConfig.ConditionPathExists =
    "/etc/sourceos/harmonia-signing.key";

  services.nginx = {
    enable = true;
    recommendedProxySettings = true;
    virtualHosts."nix-cache-local" = {
      listen = [{ addr = "127.0.0.1"; port = 8101; ssl = false; }];
      # Serve the minisig for sourceos-syncd signature verification.
      # The file is written by enroll.sh alongside harmonia key generation.
      locations."= /nix-cache-info.minisig" = {
        alias = "/etc/sourceos/nix-cache-info.minisig";
        extraConfig = ''
          default_type text/plain;
          add_header Cache-Control "no-cache";
        '';
      };
      # Proxy everything else to harmonia.
      locations."/" = {
        proxyPass = "http://127.0.0.1:8099";
        extraConfig = ''
          proxy_read_timeout 300;
        '';
      };
    };
  };

  # Allow nginx to read /etc/sourceos/nix-cache-info.minisig
  systemd.services.nginx.serviceConfig.ReadOnlyPaths = [ "/etc/sourceos" ];

  # ── Enrollment tooling ──────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [
    age
    sops
    minisign
    docker-compose
    ruby          # for hammer CLI gems
    git
    curl
    jq
    # nix-store --generate-binary-cache-key is part of the nix package (already present)
  ];

  # ── SOPS secrets ────────────────────────────────────────────────────────────
  # Stored at /etc/sourceos/secrets.yaml (NOT in the repo).
  # Generated and SOPS-encrypted by enroll.sh using the device age key.
  #
  # validateSopsFiles = false: prevents sops-nix from failing activation on
  # pass-1 nixos-rebuild (before age.key and secrets.yaml exist). The secrets
  # service runs at boot; if the files are missing it fails gracefully and
  # sourceos-syncd is gated by ConditionPathExists so it won't start either.
  sops.validateSopsFiles = false;
  sops.age.keyFile = "/etc/sourceos/age.key";
  sops.secrets.katello-password = {
    sopsFile = "/etc/sourceos/secrets.yaml";
    owner = "sourceos-syncd";
    group = "sourceos-syncd";
    mode = "0400";
  };

  # ── sourceos-syncd daemon ────────────────────────────────────────────────────
  sourceos.syncd = {
    enable = true;
    package = syncdPkg;
    sourceosBoot.package = bootPkg;
    katelloUrl = "https://127.0.0.1:8443";
    lifecycleEnv = "stable";
    locus = "local";
    flakeRef = "github:SourceOS-Linux/source-os#builder-aarch64";
    pollInterval = 300;
    noVerifySsl = true;
    katelloPasswordFile = config.sops.secrets.katello-password.path;
    # signingPublicKey is set via enroll.nix after minisign key generation.
    healthCheck = {
      enable = true;
      delayAfterBootSec = 120;
      rollbackOnFailure = true;
    };
  };

  system.stateVersion = "25.05";
}
