#!/usr/bin/env bash
# SourceOS M2 enrollment script.
#
# Run once after Asahi Linux + NixOS base install. Idempotent.
#
# Usage (run as root from the source-os repo root):
#   sudo bash scripts/enroll.sh
#
# Environment overrides:
#   SOURCEOS_REPO_ROOT        path to this repo  (default: script's parent dir)
#   PROPHET_PLATFORM_ROOT     path for prophet-platform clone
#   SOURCEOS_ORG              Katello org name   (default: SocioProphet)
#   SOURCEOS_HOST             NixOS host target  (default: builder-aarch64)

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────

REPO_ROOT="${SOURCEOS_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PROPHET_PLATFORM_ROOT="${PROPHET_PLATFORM_ROOT:-/opt/prophet-platform}"
ORG="${SOURCEOS_ORG:-SocioProphet}"
HOST="${SOURCEOS_HOST:-builder-aarch64}"

KATELLO_URL="https://127.0.0.1:8443"
KATELLO_USER="admin"
SOURCEOS_DIR="/etc/sourceos"
AGE_KEY="${SOURCEOS_DIR}/age.key"
AGE_PUB="${SOURCEOS_DIR}/age.pub"
SECRETS_YAML="${SOURCEOS_DIR}/secrets.yaml"
MINISIGN_PUB="${SOURCEOS_DIR}/nix-cache.pub"
MINISIGN_SEC="${SOURCEOS_DIR}/nix-cache.sec"
MINISIGN_CACHE_INFO="${SOURCEOS_DIR}/nix-cache-info"
MINISIGN_CACHE_INFO_SIG="${SOURCEOS_DIR}/nix-cache-info.minisig"
HARMONIA_KEY="${SOURCEOS_DIR}/harmonia-signing.key"
HARMONIA_PUB="${SOURCEOS_DIR}/harmonia-signing.pub"
KATELLO_ADMIN_PW_FILE="${SOURCEOS_DIR}/katello-admin-password"
ENROLL_NIX="${REPO_ROOT}/hosts/${HOST}/enroll.nix"
HW_CONFIG="${REPO_ROOT}/hosts/${HOST}/hardware-configuration.nix"
COMPOSE_FILE="${PROPHET_PLATFORM_ROOT}/infra/local/docker-compose.foreman-katello.yml"
COMPOSE_ENV="${PROPHET_PLATFORM_ROOT}/infra/local/foreman-katello/.env"
COMPOSE_ENV_EXAMPLE="${PROPHET_PLATFORM_ROOT}/infra/local/foreman-katello/.env.example"

TOTAL_STEPS=12
ENROLL_START=$(date +%s)

# ── Helpers ───────────────────────────────────────────────────────────────────

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

_step_start=0
step() {
    local n="$1"; shift
    _step_start=$(date +%s)
    echo
    printf "${CYAN}${BOLD}[%02d/%d]${NC} ${BOLD}%s${NC}\n" "$n" "$TOTAL_STEPS" "$*"
    printf "       %s\n" "$(printf '─%.0s' {1..55})"
}
ok()   { printf "  ${GREEN}✓${NC}  %s\n" "$*"; }
info() { printf "  ${CYAN}·${NC}  %s\n" "$*"; }
warn() { printf "  ${YELLOW}!${NC}  %s\n" "$*"; }
die()  { printf "  ${RED}✗  ERROR:${NC} %s\n" "$*" >&2; exit 1; }
elapsed() { echo $(( $(date +%s) - _step_start ))s; }

require_cmd() { command -v "$1" &>/dev/null || die "'$1' not found — did pass-1 nixos-rebuild complete?"; }

wait_for_url() {
    local url="$1" label="${2:-service}" max="${3:-120}" interval=5 n=0
    info "Waiting for ${label}..."
    while ! curl -fsSk --max-time 5 "$url" &>/dev/null; do
        sleep $interval; n=$((n + interval))
        [[ $n -ge $max ]] && die "${label} not ready at ${url} after ${max}s"
        [[ $((n % 30)) -eq 0 ]] && info "  still waiting (${n}s)..."
    done
    ok "${label} is up"
}

gen_password() { head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 24; }

write_enroll_nix() {
    local signing_pub="$1" harmonia_pub_key="$2"
    cat > "${ENROLL_NIX}" <<NIX
# Generated by scripts/enroll.sh — device-specific, gitignored.
# Re-run scripts/enroll.sh to regenerate.
{ ... }:
{
  sourceos.syncd.signingPublicKey = "${signing_pub}";
  nix.settings.trusted-public-keys = [ "${harmonia_pub_key}" ];
}
NIX
    ok "Wrote ${ENROLL_NIX}"
}

banner() {
    local total=$(( $(date +%s) - ENROLL_START ))
    echo
    printf "${GREEN}${BOLD}"
    printf "╔══════════════════════════════════════════════════════════════╗\n"
    printf "║        SourceOS builder-aarch64 enrollment complete         ║\n"
    printf "╚══════════════════════════════════════════════════════════════╝\n"
    printf "${NC}"
    echo
    printf "  %-28s %s\n" "Total time:"          "${total}s"
    printf "  %-28s %s\n" "Age key:"             "${AGE_KEY}"
    printf "  %-28s %s\n" "Secrets:"             "${SECRETS_YAML}"
    printf "  %-28s %s\n" "Signing public key:"  "${MINISIGN_PUB}"
    printf "  %-28s %s\n" "Harmonia cache key:"  "${HARMONIA_PUB}"
    printf "  %-28s %s\n" "Katello UI:"          "${KATELLO_URL}"
    printf "  %-28s %s\n" "Katello password:"    "$(cat ${KATELLO_ADMIN_PW_FILE} 2>/dev/null || echo '(see file)')"
    echo
    printf "  ${BOLD}Next steps:${NC}\n"
    printf "  %-28s %s\n" "Daemon status:"       "systemctl status sourceos-syncd"
    printf "  %-28s %s\n" "Live logs:"           "journalctl -u sourceos-syncd -f"
    printf "  %-28s %s\n" "Last receipt:"        "sourceos-syncd receipts last"
    printf "  %-28s %s\n" "Full health check:"   "bash scripts/doctor.sh"
    echo
}

# ── Step 0: Preflight ─────────────────────────────────────────────────────────

step 0 "Preflight checks"

[[ $EUID -eq 0 ]]              || die "Run as root: sudo bash scripts/enroll.sh"
[[ -d /nix ]]                  || die "Not a NixOS system (/nix not found)"
[[ -f "${REPO_ROOT}/flake.nix" ]] || die "flake.nix not found — set SOURCEOS_REPO_ROOT"

# Disk space: require at least 100 GB free on the partition holding the repo
DISK_FREE_KB=$(df -k "${REPO_ROOT}" | awk 'NR==2 {print $4}')
DISK_FREE_GB=$(( DISK_FREE_KB / 1024 / 1024 ))
[[ $DISK_FREE_GB -ge 100 ]] || \
    die "Insufficient disk space: ${DISK_FREE_GB} GB free, 100 GB required"

# Network connectivity
curl -fsSL --max-time 10 https://api.github.com >/dev/null 2>&1 || \
    die "No network or GitHub unreachable — enrollment requires internet access"

mkdir -p "${SOURCEOS_DIR}" && chmod 700 "${SOURCEOS_DIR}"

info "Repo root:   ${REPO_ROOT}"
info "Host target: ${HOST}"
info "Katello org: ${ORG}"
info "Disk free:   ${DISK_FREE_GB} GB"
ok   "Preflight passed ($(elapsed))"

# ── Step 1: hardware-configuration.nix ───────────────────────────────────────

step 1 "Hardware configuration"

if [[ -f "${HW_CONFIG}" ]]; then
    ok "hardware-configuration.nix already present"
else
    nixos-generate-config --show-hardware-config > "${HW_CONFIG}"
    ok "Generated ${HW_CONFIG} ($(elapsed))"
fi

# ── Step 2: nixos-rebuild pass 1 ─────────────────────────────────────────────

step 2 "nixos-rebuild switch — pass 1 (installs Docker, age, sops, minisign)"

# --impure is required: hardware-configuration.nix and enroll.nix are gitignored
# and therefore not copied into the Nix store. --impure lets Nix access them
# from the working directory via builtins.pathExists and direct import.
info "Building... (5-15 min on first run, downloads packages)"
PASS1_LOG="/tmp/sourceos-enroll-pass1-$(date +%s).log"
nixos-rebuild switch --flake "${REPO_ROOT}#${HOST}" --impure 2>&1 | \
    tee "${PASS1_LOG}" | \
    grep -E '(building|fetching|error|warning|Error|FAILED|activating)' || true
# Check exit code of nixos-rebuild (not the grep)
if ! grep -q 'activating' "${PASS1_LOG}" 2>/dev/null; then
    # activating line may be absent on cached builds; check for explicit failure
    if grep -qiE '(error:|FAILED|failed to)' "${PASS1_LOG}" 2>/dev/null; then
        die "Pass 1 rebuild failed. Full log: ${PASS1_LOG}
    Check: journalctl -xe | tail -50"
    fi
fi
ok "Pass 1 complete ($(elapsed)) — log: ${PASS1_LOG}"

# ── Step 3: Age key ───────────────────────────────────────────────────────────

step 3 "Device age key"

require_cmd age-keygen

if [[ -f "${AGE_KEY}" ]]; then
    ok "Age key already exists"
else
    age-keygen -o "${AGE_KEY}" 2>/dev/null
    chmod 600 "${AGE_KEY}"
    ok "Generated ${AGE_KEY} ($(elapsed))"
fi
AGE_PUBKEY=$(age-keygen -y "${AGE_KEY}")
echo "${AGE_PUBKEY}" > "${AGE_PUB}"
info "Public key: ${AGE_PUBKEY}"

# If secrets.yaml already exists, verify it is decryptable with the current key.
# A mismatch means the age key changed (e.g. disk copy or manual deletion) and
# the old ciphertext can never be recovered — catch it now, not at boot.
if [[ -f "${SECRETS_YAML}" ]]; then
    SOPS_AGE_KEY_FILE="${AGE_KEY}" sops -d "${SECRETS_YAML}" >/dev/null 2>&1 || \
        die "secrets.yaml exists but CANNOT be decrypted with the current age key.
    This means the age key was replaced after secrets were encrypted.
    To re-enroll: rm -f ${SECRETS_YAML} ${AGE_KEY} ${AGE_PUB}
    Then re-run: sudo bash scripts/enroll.sh"
    info "secrets.yaml verified decryptable with current age key"
fi

# ── Step 4: Foreman+Katello ───────────────────────────────────────────────────

step 4 "Foreman+Katello (docker compose up)"

require_cmd docker
require_cmd docker-compose

if [[ ! -d "${PROPHET_PLATFORM_ROOT}" ]]; then
    info "Cloning prophet-platform..."
    mkdir -p "$(dirname "${PROPHET_PLATFORM_ROOT}")" || \
        die "Cannot create $(dirname "${PROPHET_PLATFORM_ROOT}") — check disk and permissions"
    git clone git@github.com:SocioProphet/prophet-platform.git "${PROPHET_PLATFORM_ROOT}" 2>/dev/null || \
        git clone https://github.com/SocioProphet/prophet-platform.git "${PROPHET_PLATFORM_ROOT}" || \
        die "Failed to clone prophet-platform. Check network and GitHub access (SSH key or HTTPS)."
fi

if [[ ! -f "${COMPOSE_ENV}" ]]; then
    info "Generating Foreman+Katello .env (random passwords)..."
    FOREMAN_ADMIN_PASSWORD=$(gen_password)
    KATELLO_PG_PASSWORD=$(gen_password)

    cp "${COMPOSE_ENV_EXAMPLE}" "${COMPOSE_ENV}"
    sed -i "s|^FOREMAN_ADMIN_PASSWORD=.*|FOREMAN_ADMIN_PASSWORD=${FOREMAN_ADMIN_PASSWORD}|" "${COMPOSE_ENV}"
    sed -i "s|^KATELLO_PG_PASSWORD=.*|KATELLO_PG_PASSWORD=${KATELLO_PG_PASSWORD}|" "${COMPOSE_ENV}"
    chmod 600 "${COMPOSE_ENV}"

    echo "${FOREMAN_ADMIN_PASSWORD}" > "${KATELLO_ADMIN_PW_FILE}"
    chmod 600 "${KATELLO_ADMIN_PW_FILE}"
    ok "Generated .env"
else
    ok ".env already exists"
fi

KATELLO_PASSWORD=$(cat "${KATELLO_ADMIN_PW_FILE}")

docker-compose -f "${COMPOSE_FILE}" --env-file "${COMPOSE_ENV}" up -d
info "Containers started. Waiting for foreman-installer (10-15 min)..."
info "Follow: docker compose -f ${COMPOSE_FILE} logs -f foreman-katello"

MAX_WAIT="${FOREMAN_WAIT_TIMEOUT:-1800}"; ELAPSED=0; INTERVAL=15
while ! docker exec katello-foreman test -f /var/lib/foreman/.sourceos-initialized 2>/dev/null; do
    sleep $INTERVAL; ELAPSED=$((ELAPSED + INTERVAL))
    if [[ $ELAPSED -ge $MAX_WAIT ]]; then
        echo
        warn "Foreman installer still running after ${MAX_WAIT}s."
        warn "Options:"
        warn "  Watch:   docker exec katello-foreman tail -f /var/log/foreman-installer/foreman-installer.log"
        warn "  Restart: docker compose -f ${COMPOSE_FILE} restart foreman-katello"
        warn "  Re-run:  bash scripts/enroll.sh  (will skip Foreman if already complete)"
        die  "Timed out. Increase timeout: FOREMAN_WAIT_TIMEOUT=3600 bash scripts/enroll.sh"
    fi
    [[ $((ELAPSED % 60)) -eq 0 ]] && info "  foreman-installer running (${ELAPSED}s / ${MAX_WAIT}s)..."
done

wait_for_url "${KATELLO_URL}/api/v2/status" "Foreman API" 120
ok "Foreman+Katello ready ($(elapsed))"

# ── Step 5: Katello content structure ─────────────────────────────────────────

step 5 "Katello content structure"

FOREMAN_URL="${KATELLO_URL}" FOREMAN_USER="${KATELLO_USER}" \
FOREMAN_PASSWORD="${KATELLO_PASSWORD}" ORG="${ORG}" \
bash "${REPO_ROOT}/scripts/katello-sourceos-setup.sh"

ok "Org, product, repos, content view ready ($(elapsed))"

# ── Step 6: SOPS-encrypted secrets ───────────────────────────────────────────

step 6 "Encrypt secrets with SOPS"

require_cmd sops

_needs_encrypt=0
if [[ -f "${SECRETS_YAML}" ]]; then
    if python3 -c "
import json, sys
d = open('${SECRETS_YAML}').read()
if 'sops' not in d: sys.exit(1)
" 2>/dev/null; then
        ok "secrets.yaml already SOPS-encrypted"
    else
        warn "secrets.yaml exists but is not encrypted — re-encrypting"
        _needs_encrypt=1
    fi
else
    _needs_encrypt=1
fi

if [[ "${_needs_encrypt}" -eq 1 ]]; then
    PLAINTEXT=$(mktemp /tmp/sourceos-secrets-XXXXXX.yaml)
    trap "rm -f ${PLAINTEXT}" EXIT
    printf 'katello-password: "%s"\n' "${KATELLO_PASSWORD}" > "${PLAINTEXT}"
    SOPS_AGE_RECIPIENTS="${AGE_PUBKEY}" sops --encrypt "${PLAINTEXT}" > "${SECRETS_YAML}"
    chmod 600 "${SECRETS_YAML}"
    rm -f "${PLAINTEXT}"; trap - EXIT
    ok "Encrypted secrets written to ${SECRETS_YAML} ($(elapsed))"
fi

# ── Step 7: harmonia binary cache signing key ─────────────────────────────────

step 7 "harmonia binary cache signing key"

if [[ -f "${HARMONIA_KEY}" && -f "${HARMONIA_PUB}" ]]; then
    ok "harmonia signing key already exists"
elif [[ -f "${HARMONIA_KEY}" || -f "${HARMONIA_PUB}" ]]; then
    # Partial state: one file exists but not the other. Regenerating would produce
    # a new key that orphans any packages signed with the old key. Fail loudly.
    die "Partial harmonia key state detected (one of key/pub missing).
    Delete both and re-run:
      rm -f ${HARMONIA_KEY} ${HARMONIA_PUB}
      sudo bash scripts/enroll.sh"
else
    # nix-store --generate-binary-cache-key <name> <secret-key-file> <public-key-file>
    nix-store --generate-binary-cache-key "builder-aarch64-1" "${HARMONIA_KEY}" "${HARMONIA_PUB}"
    chmod 600 "${HARMONIA_KEY}"
    ok "Generated harmonia signing key ($(elapsed))"
fi

HARMONIA_PUBKEY=$(cat "${HARMONIA_PUB}")
info "harmonia public key: ${HARMONIA_PUBKEY}"

# ── Step 8: minisign key pair + nix-cache-info signature ──────────────────────

step 8 "minisign key pair and nix-cache-info signature"

require_cmd minisign

if [[ -f "${MINISIGN_PUB}" && -f "${MINISIGN_SEC}" ]]; then
    ok "minisign key pair already exists"
elif [[ -f "${MINISIGN_PUB}" || -f "${MINISIGN_SEC}" ]]; then
    die "Partial minisign key state detected (one of pub/sec missing).
    Delete both and re-run:
      rm -f ${MINISIGN_PUB} ${MINISIGN_SEC}
      sudo bash scripts/enroll.sh"
else
    info "Generating minisign key pair (no passphrase — press Enter twice if prompted)..."
    minisign -G -p "${MINISIGN_PUB}" -s "${MINISIGN_SEC}" -W
    chmod 600 "${MINISIGN_SEC}"
    ok "Generated ${MINISIGN_PUB} ($(elapsed))"
fi

SIGNING_PUBKEY=$(grep -v '^untrusted comment' "${MINISIGN_PUB}" | head -1)
info "Signing public key: ${SIGNING_PUBKEY}"

# Write nix-cache-info and sign it. nginx serves the .minisig file alongside
# harmonia so sourceos-syncd can verify the cache before pulling packages.
cat > "${MINISIGN_CACHE_INFO}" <<EOF
StoreDir: /nix/store
WantMassQuery: 1
Priority: 40
EOF

minisign -S -s "${MINISIGN_SEC}" -m "${MINISIGN_CACHE_INFO}" -x "${MINISIGN_CACHE_INFO_SIG}" \
    || die "minisign signing failed — check that ${MINISIGN_SEC} passphrase is empty"
ok "Signed nix-cache-info → ${MINISIGN_CACHE_INFO_SIG} ($(elapsed))"

# ── Step 9: Write enroll.nix (replaces old sed-patching approach) ─────────────

step 9 "Write enroll.nix (device-specific NixOS settings)"

write_enroll_nix "${SIGNING_PUBKEY}" "${HARMONIA_PUBKEY}"
ok "enroll.nix written — no Nix file patching needed ($(elapsed))"

# ── Step 10: Build + push NixOS closure to local cache ────────────────────────

step 10 "Build NixOS closure + push to harmonia cache"

info "Building builder-aarch64 system closure..."
CLOSURE=$(nix build "${REPO_ROOT}#nixosConfigurations.${HOST}.config.system.build.toplevel" \
    --no-link --print-out-paths 2>&1 | tail -1)
ok "Built: ${CLOSURE}"

# Harmonia must be running before we can push (it starts after pass-2 rebuild).
# We push after pass-2. Skip here and record for the next step.
info "Closure push to harmonia will happen after pass-2 rebuild in step 11."

# ── Step 11: nixos-rebuild pass 2 (live config with all secrets + keys) ───────

step 11 "nixos-rebuild switch — pass 2 (live config: secrets, signing key, harmonia)"

info "Activating final configuration..."
PASS2_LOG="/tmp/sourceos-enroll-pass2-$(date +%s).log"
nixos-rebuild switch --flake "${REPO_ROOT}#${HOST}" --impure 2>&1 | \
    tee "${PASS2_LOG}" | \
    grep -E '(building|fetching|error|warning|Error|FAILED|activating)' || true
if grep -qiE '(error:|FAILED|failed to)' "${PASS2_LOG}" 2>/dev/null; then
    die "Pass 2 rebuild failed. Full log: ${PASS2_LOG}
    Check: journalctl -xe | tail -50
    The previous generation (pass 1) is still bootable."
fi
ok "Pass 2 complete ($(elapsed)) — log: ${PASS2_LOG}"

# Now push the closure to the running harmonia cache
info "Pushing NixOS closure to local harmonia cache (http://127.0.0.1:8101)..."
sleep 3  # brief pause for harmonia to finish starting
if curl -fsSk http://127.0.0.1:8101/nix-cache-info &>/dev/null; then
    nix copy --to "http://127.0.0.1:8101" "${CLOSURE}" && \
        ok "Closure pushed to harmonia cache" || \
        warn "nix copy failed — run manually: nix copy --to 'http://127.0.0.1:8101' ${CLOSURE}"
else
    warn "harmonia not yet responding on :8101 — push manually after it starts"
    warn "  nix copy --to 'http://127.0.0.1:8101' ${CLOSURE}"
fi

# Promote content view to stable so sourceos-syncd can pick it up
info "Promoting content view to stable..."
CV_VERSION=$(docker exec katello-foreman hammer \
    --server "${KATELLO_URL}" --username "${KATELLO_USER}" --password "${KATELLO_PASSWORD}" \
    --output json content-view version list \
    --organization "${ORG}" --content-view "sourceos-builder-aarch64" 2>/dev/null | \
    python3 -c "import json,sys; vs=json.load(sys.stdin); print(sorted(vs,key=lambda v:v['ID'])[-1]['Version'])" \
    2>/dev/null || echo "")

if [[ -n "${CV_VERSION}" ]]; then
    for env in candidate stable; do
        docker exec katello-foreman hammer \
            --server "${KATELLO_URL}" --username "${KATELLO_USER}" --password "${KATELLO_PASSWORD}" \
            content-view version promote \
            --organization "${ORG}" \
            --content-view "sourceos-builder-aarch64" \
            --version "${CV_VERSION}" \
            --to-lifecycle-environment "${env}" 2>/dev/null && \
            ok "Promoted to ${env}" || info "Already at ${env} (or skipping)"
    done
else
    warn "Could not determine CV version — promote manually after Katello sync completes"
fi

# ── Step 12: Verify ────────────────────────────────────────────────────────────

step 12 "Verify enrollment"

sleep 10  # let sourceos-syncd start up

HEALTHY=1
if systemctl is-active --quiet sourceos-syncd 2>/dev/null; then
    ok "sourceos-syncd: active"
else
    warn "sourceos-syncd not active yet (may still be starting)"
    HEALTHY=0
fi

if systemctl is-active --quiet harmonia 2>/dev/null; then
    ok "harmonia: active"
else
    warn "harmonia not active yet"
    HEALTHY=0
fi

if systemctl is-active --quiet nginx 2>/dev/null; then
    ok "nginx (nix-cache proxy): active"
    if curl -fsSk http://127.0.0.1:8101/nix-cache-info &>/dev/null; then
        ok "Nix cache at http://127.0.0.1:8101 responding"
    fi
    if curl -fsSk http://127.0.0.1:8101/nix-cache-info.minisig &>/dev/null; then
        ok "minisig endpoint serving correctly"
    else
        warn "minisig not yet at /nix-cache-info.minisig — check nginx + ${MINISIGN_CACHE_INFO_SIG}"
    fi
fi

if [[ $HEALTHY -eq 1 ]]; then
    ok "All services healthy ($(elapsed))"
else
    warn "Some services not yet active. Run: sudo bash scripts/doctor.sh"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

banner
