#!/usr/bin/env bash
# SourceOS M2 enrollment script.
#
# Run once after Asahi Linux + NixOS base install. Idempotent.
#
# Usage (run as root from the source-os repo root):
#   sudo bash scripts/enroll.sh
#
# Environment overrides:
#   SOURCEOS_REPO_ROOT        path to this repo  (default: script's parent dir)
#   PROPHET_PLATFORM_ROOT     path for prophet-platform clone
#   SOURCEOS_ORG              Katello org name   (default: SocioProphet)
#   SOURCEOS_HOST             NixOS host target  (default: builder-aarch64)

set -euo pipefail
# All files created by this script default to owner-only permissions.
# Explicit chmod 600/700 calls remain as documented intent, but umask is the
# first line of defence against a window where a secret file is world-readable.
umask 077

# ── Config ────────────────────────────────────────────────────────────────────

REPO_ROOT="${SOURCEOS_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PROPHET_PLATFORM_ROOT="${PROPHET_PLATFORM_ROOT:-/opt/prophet-platform}"
ORG="${SOURCEOS_ORG:-SocioProphet}"
HOST="${SOURCEOS_HOST:-builder-aarch64}"

KATELLO_URL="https://127.0.0.1:8443"
KATELLO_USER="admin"
SOURCEOS_DIR="/etc/sourceos"
AGE_KEY="${SOURCEOS_DIR}/age.key"
AGE_PUB="${SOURCEOS_DIR}/age.pub"
SECRETS_YAML="${SOURCEOS_DIR}/secrets.yaml"
MINISIGN_PUB="${SOURCEOS_DIR}/nix-cache.pub"
MINISIGN_SEC="${SOURCEOS_DIR}/nix-cache.sec"
MINISIGN_CACHE_INFO="${SOURCEOS_DIR}/nix-cache-info"
MINISIGN_CACHE_INFO_SIG="${SOURCEOS_DIR}/nix-cache-info.minisig"
HARMONIA_KEY="${SOURCEOS_DIR}/harmonia-signing.key"
HARMONIA_PUB="${SOURCEOS_DIR}/harmonia-signing.pub"
KATELLO_ADMIN_PW_FILE="${SOURCEOS_DIR}/katello-admin-password"
ENROLL_NIX="${REPO_ROOT}/hosts/${HOST}/enroll.nix"
HW_CONFIG="${REPO_ROOT}/hosts/${HOST}/hardware-configuration.nix"
COMPOSE_FILE="${PROPHET_PLATFORM_ROOT}/infra/local/docker-compose.foreman-katello.yml"
COMPOSE_ENV="${PROPHET_PLATFORM_ROOT}/infra/local/foreman-katello/.env"
COMPOSE_ENV_EXAMPLE="${PROPHET_PLATFORM_ROOT}/infra/local/foreman-katello/.env.example"

TOTAL_STEPS=12
ENROLL_START=$(date +%s)

# ── Helpers ───────────────────────────────────────────────────────────────────

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

_step_start=0
step() {
    local n="$1"; shift
    _step_start=$(date +%s)
    echo
    printf "${CYAN}${BOLD}[%02d/%d]${NC} ${BOLD}%s${NC}\n" "$n" "$TOTAL_STEPS" "$*"
    printf "       %s\n" "$(printf '─%.0s' {1..55})"
}
ok()   { printf "  ${GREEN}✓${NC}  %s\n" "$*"; }
info() { printf "  ${CYAN}·${NC}  %s\n" "$*"; }
warn() { printf "  ${YELLOW}!${NC}  %s\n" "$*"; }
die()  { printf "  ${RED}✗  ERROR:${NC} %s\n" "$*" >&2; exit 1; }
elapsed() { echo $(( $(date +%s) - _step_start ))s; }

require_cmd() { command -v "$1" &>/dev/null || die "'$1' not found — did pass-1 nixos-rebuild complete?"; }

wait_for_url() {
    local url="$1" label="${2:-service}" max="${3:-120}" interval=5 n=0
    info "Waiting for ${label}..."
    while ! curl -fsSk --max-time 5 "$url" &>/dev/null; do
        sleep $interval; n=$((n + interval))
        [[ $n -ge $max ]] && die "${label} not ready at ${url} after ${max}s"
        [[ $((n % 30)) -eq 0 ]] && info "  still waiting (${n}s)..."
    done
    ok "${label} is up"
}

gen_password() {
    local pw
    pw=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 24)
    # Paranoia: tr -d can strip enough chars to produce a short result.
    [[ ${#pw} -ge 16 ]] || { echo "gen_password produced a short result (${#pw} chars) — retry" >&2; return 1; }
    printf '%s' "${pw}"
}

write_enroll_nix() {
    local signing_pub="$1" harmonia_pub_key="$2"
    # Write to a temp file then atomically rename so a partial write never leaves
    # a syntactically broken enroll.nix that silently poisons the next rebuild.
    cat > "${ENROLL_NIX}.tmp" <<NIX
# Generated by scripts/enroll.sh — device-specific, gitignored.
# Re-run scripts/enroll.sh to regenerate.
{ ... }:
{
  sourceos.syncd.signingPublicKey = "${signing_pub}";
  nix.settings.trusted-public-keys = [ "${harmonia_pub_key}" ];
}
NIX
    mv "${ENROLL_NIX}.tmp" "${ENROLL_NIX}"
    ok "Wrote ${ENROLL_NIX}"
}

banner() {
    local total=$(( $(date +%s) - ENROLL_START ))
    echo
    printf "${GREEN}${BOLD}"
    printf "╔══════════════════════════════════════════════════════════════╗\n"
    printf "║        SourceOS builder-aarch64 enrollment complete         ║\n"
    printf "╚══════════════════════════════════════════════════════════════╝\n"
    printf "${NC}"
    echo
    printf "  %-28s %s\n" "Total time:"          "${total}s"
    printf "  %-28s %s\n" "Age key:"             "${AGE_KEY}"
    printf "  %-28s %s\n" "Secrets:"             "${SECRETS_YAML}"
    printf "  %-28s %s\n" "Signing public key:"  "${MINISIGN_PUB}"
    printf "  %-28s %s\n" "Harmonia cache key:"  "${HARMONIA_PUB}"
    printf "  %-28s %s\n" "Katello UI:"          "${KATELLO_URL}"
    printf "  %-28s %s\n" "Katello password:"    "$(cat "${KATELLO_ADMIN_PW_FILE}" 2>/dev/null || echo '(see file)')"
    echo
    printf "  ${BOLD}Next steps:${NC}\n"
    printf "  %-28s %s\n" "Daemon status:"       "systemctl status sourceos-syncd"
    printf "  %-28s %s\n" "Live logs:"           "journalctl -u sourceos-syncd -f"
    printf "  %-28s %s\n" "Last receipt:"        "sourceos-syncd receipts last"
    printf "  %-28s %s\n" "Full health check:"   "bash scripts/doctor.sh"
    echo
}

# ── Step 0: Preflight ─────────────────────────────────────────────────────────

step 0 "Preflight checks"

[[ $EUID -eq 0 ]]              || die "Run as root: sudo bash scripts/enroll.sh"
[[ -d /nix ]]                  || die "Not a NixOS system (/nix not found)"
[[ -f "${REPO_ROOT}/flake.nix" ]] || die "flake.nix not found — set SOURCEOS_REPO_ROOT"
[[ -d "${REPO_ROOT}/hosts/${HOST}" ]] || \
    die "Host directory not found: ${REPO_ROOT}/hosts/${HOST}
    Set SOURCEOS_HOST to a valid host. Available: $(ls "${REPO_ROOT}/hosts/" 2>/dev/null | tr '\n' ' ')"

# Disk space: require at least 100 GB free on the partition holding the repo
DISK_FREE_KB=$(df -k "${REPO_ROOT}" | awk 'NR==2 {print $4}')
[[ "${DISK_FREE_KB}" =~ ^[0-9]+$ ]] || \
    die "Could not parse available disk space from 'df -k ${REPO_ROOT}' (got: '${DISK_FREE_KB}')"
DISK_FREE_GB=$(( DISK_FREE_KB / 1024 / 1024 ))
[[ $DISK_FREE_GB -ge 100 ]] || \
    die "Insufficient disk space: ${DISK_FREE_GB} GB free, 100 GB required"

# Network connectivity
curl -fsSL --max-time 10 https://api.github.com >/dev/null 2>&1 || \
    die "No network or GitHub unreachable — enrollment requires internet access"

mkdir -p "${SOURCEOS_DIR}" && chmod 700 "${SOURCEOS_DIR}"

info "Repo root:   ${REPO_ROOT}"
info "Host target: ${HOST}"
info "Katello org: ${ORG}"
info "Disk free:   ${DISK_FREE_GB} GB"
ok   "Preflight passed ($(elapsed))"

# ── Step 1: hardware-configuration.nix ───────────────────────────────────────

step 1 "Hardware configuration"

rm -f "${HW_CONFIG}.tmp"  # clean up any stale temp from a previous interrupted run

if [[ -f "${HW_CONFIG}" ]]; then
    ok "hardware-configuration.nix already present"
else
    # Write to a temp file first. `nixos-generate-config > HW_CONFIG` would truncate
    # HW_CONFIG to zero bytes before the command runs; if the command then fails,
    # the empty file remains and subsequent idempotent re-runs skip generation while
    # pass-1 nixos-rebuild fails with a confusing empty-import Nix error.
    nixos-generate-config --show-hardware-config > "${HW_CONFIG}.tmp" || \
        die "nixos-generate-config failed — check: journalctl -xe | tail -30"
    [[ -s "${HW_CONFIG}.tmp" ]] || die "nixos-generate-config produced empty output — check: journalctl -xe"
    mv "${HW_CONFIG}.tmp" "${HW_CONFIG}"
    ok "Generated ${HW_CONFIG} ($(elapsed))"
fi

# ── Step 2: nixos-rebuild pass 1 ─────────────────────────────────────────────

step 2 "nixos-rebuild switch — pass 1 (installs Docker, age, sops, minisign)"

# --impure is required: hardware-configuration.nix and enroll.nix are gitignored
# and therefore not copied into the Nix store. --impure lets Nix access them
# from the working directory via builtins.pathExists and direct import.
info "Building... (5-15 min on first run, downloads packages)"
PASS1_LOG="/tmp/sourceos-enroll-pass1-$(date +%s).log"
# `|| true` resets PIPESTATUS to [0] — do NOT use it here. Instead bracket with
# set +e so that grep exiting 1 (no matching lines on a cached build) does not
# abort the script, while PIPESTATUS[0] still carries nixos-rebuild's real exit code.
set +e
nixos-rebuild switch --flake "${REPO_ROOT}#${HOST}" --impure 2>&1 | \
    tee "${PASS1_LOG}" | \
    grep --line-buffered -E '(building|fetching|error|warning|Error|FAILED|activating)'
NB1_EXIT=${PIPESTATUS[0]}
set -e
[[ $NB1_EXIT -eq 0 ]] || die "Pass 1 rebuild failed (exit ${NB1_EXIT}). Full log: ${PASS1_LOG}
    Check: journalctl -xe | tail -50"
ok "Pass 1 complete ($(elapsed)) — log: ${PASS1_LOG}"

# ── Step 3: Age key ───────────────────────────────────────────────────────────

step 3 "Device age key"

rm -f "${AGE_KEY}.tmp"  # clean up stale temp from a previous interrupted run
require_cmd age-keygen

if [[ -f "${AGE_KEY}" ]]; then
    ok "Age key already exists"
else
    # Capture stdout so the write is atomic: age-keygen -o FILE truncates before
    # writing, leaving a corrupt partial file if interrupted. Stdout capture +
    # mv means re-runs see no file (and regenerate) rather than a corrupt one.
    age-keygen 2>/dev/null > "${AGE_KEY}.tmp"
    [[ -s "${AGE_KEY}.tmp" ]] || die "age-keygen produced empty output — check age installation"
    mv "${AGE_KEY}.tmp" "${AGE_KEY}"
    chmod 600 "${AGE_KEY}"
    ok "Generated ${AGE_KEY} ($(elapsed))"
fi
AGE_PUBKEY=$(age-keygen -y "${AGE_KEY}" 2>/dev/null) || \
    die "age-keygen -y failed — ${AGE_KEY} may be corrupt or in an unsupported format.
    Regenerate: rm -f ${AGE_KEY} ${AGE_PUB} ${SECRETS_YAML} && sudo bash scripts/enroll.sh"
[[ -n "${AGE_PUBKEY}" ]] || \
    die "age-keygen produced empty public key from ${AGE_KEY} — key file may be corrupt.
    Regenerate: rm -f ${AGE_KEY} ${AGE_PUB} ${SECRETS_YAML} && sudo bash scripts/enroll.sh"
# Atomic write — consistent with all other file writes in this script.
printf '%s\n' "${AGE_PUBKEY}" > "${AGE_PUB}.tmp" && mv "${AGE_PUB}.tmp" "${AGE_PUB}"
info "Public key: ${AGE_PUBKEY}"

# If secrets.yaml already exists, verify it is decryptable with the current key.
# A mismatch means the age key changed (e.g. disk copy or manual deletion) and
# the old ciphertext can never be recovered — catch it now, not at boot.
if [[ -f "${SECRETS_YAML}" ]]; then
    SOPS_AGE_KEY_FILE="${AGE_KEY}" sops -d "${SECRETS_YAML}" >/dev/null 2>&1 || \
        die "secrets.yaml exists but CANNOT be decrypted with the current age key.
    This means the age key was replaced after secrets were encrypted.
    To re-enroll: rm -f ${SECRETS_YAML} ${AGE_KEY} ${AGE_PUB}
    Then re-run: sudo bash scripts/enroll.sh"
    info "secrets.yaml verified decryptable with current age key"
fi

# ── Step 4: Foreman+Katello ───────────────────────────────────────────────────

step 4 "Foreman+Katello (docker compose up)"

require_cmd docker
require_cmd docker-compose

if [[ ! -d "${PROPHET_PLATFORM_ROOT}" ]]; then
    info "Cloning prophet-platform..."
    mkdir -p "$(dirname "${PROPHET_PLATFORM_ROOT}")" || \
        die "Cannot create $(dirname "${PROPHET_PLATFORM_ROOT}") — check disk and permissions"
    git clone git@github.com:SocioProphet/prophet-platform.git "${PROPHET_PLATFORM_ROOT}" 2>/dev/null || \
        git clone https://github.com/SocioProphet/prophet-platform.git "${PROPHET_PLATFORM_ROOT}" || \
        die "Failed to clone prophet-platform. Check network and GitHub access (SSH key or HTTPS)."
fi

if [[ ! -f "${COMPOSE_ENV}" ]]; then
    info "Generating Foreman+Katello .env (random passwords)..."
    FOREMAN_ADMIN_PASSWORD=$(gen_password)
    KATELLO_PG_PASSWORD=$(gen_password)

    [[ -f "${COMPOSE_ENV_EXAMPLE}" ]] || \
        die "Missing ${COMPOSE_ENV_EXAMPLE} — prophet-platform clone may be incomplete or the compose layout changed"
    # install -m 600 is atomic: creates the file with correct permissions in one
    # syscall. A plain `cp` followed by `chmod 600` leaves a window where the
    # file (containing plaintext passwords) is world-readable.
    install -m 600 "${COMPOSE_ENV_EXAMPLE}" "${COMPOSE_ENV}"
    # Verify the expected keys exist before substituting — if the template
    # changes to use different key names, sed exits 0 silently with no change
    # and Foreman boots with the example placeholder passwords.
    grep -q '^FOREMAN_ADMIN_PASSWORD=' "${COMPOSE_ENV}" || \
        die "FOREMAN_ADMIN_PASSWORD key missing from ${COMPOSE_ENV_EXAMPLE} — template may have changed"
    grep -q '^KATELLO_PG_PASSWORD=' "${COMPOSE_ENV}" || \
        die "KATELLO_PG_PASSWORD key missing from ${COMPOSE_ENV_EXAMPLE} — template may have changed"
    sed -i "s|^FOREMAN_ADMIN_PASSWORD=.*|FOREMAN_ADMIN_PASSWORD=${FOREMAN_ADMIN_PASSWORD}|" "${COMPOSE_ENV}"
    sed -i "s|^KATELLO_PG_PASSWORD=.*|KATELLO_PG_PASSWORD=${KATELLO_PG_PASSWORD}|" "${COMPOSE_ENV}"
    # Confirm both substitutions actually landed — paranoia against sed edge cases.
    grep -q "^FOREMAN_ADMIN_PASSWORD=${FOREMAN_ADMIN_PASSWORD}" "${COMPOSE_ENV}" || \
        die "sed failed to set FOREMAN_ADMIN_PASSWORD in ${COMPOSE_ENV}"
    grep -q "^KATELLO_PG_PASSWORD=${KATELLO_PG_PASSWORD}" "${COMPOSE_ENV}" || \
        die "sed failed to set KATELLO_PG_PASSWORD in ${COMPOSE_ENV}"

    # Atomic write: if the script is killed mid-write the file stays absent
    # rather than being empty, so a re-run regenerates it rather than reading
    # an empty password and dying on the KATELLO_PASSWORD guard below.
    printf '%s\n' "${FOREMAN_ADMIN_PASSWORD}" > "${KATELLO_ADMIN_PW_FILE}.tmp"
    mv "${KATELLO_ADMIN_PW_FILE}.tmp" "${KATELLO_ADMIN_PW_FILE}"
    ok "Generated .env"
else
    ok ".env already exists"
fi

[[ -f "${KATELLO_ADMIN_PW_FILE}" ]] || \
    die "Katello password file missing: ${KATELLO_ADMIN_PW_FILE}
    Regenerate: rm -f ${COMPOSE_ENV} && sudo bash scripts/enroll.sh"
KATELLO_PASSWORD=$(cat "${KATELLO_ADMIN_PW_FILE}")
[[ -n "${KATELLO_PASSWORD}" ]] || \
    die "Katello password file is empty: ${KATELLO_ADMIN_PW_FILE}
    Regenerate: rm -f ${KATELLO_ADMIN_PW_FILE} ${COMPOSE_ENV} && sudo bash scripts/enroll.sh"

[[ -f "${COMPOSE_FILE}" ]] || \
    die "docker-compose file not found: ${COMPOSE_FILE}
    The prophet-platform repo layout may have changed.
    Check: ls $(dirname "${COMPOSE_FILE}")"

docker-compose -f "${COMPOSE_FILE}" --env-file "${COMPOSE_ENV}" up -d

# Verify that compose actually started containers — `up -d` exits 0 even if
# containers crash-loop immediately. Count running containers for this project.
_KATELLO_RUNNING=$(docker ps --filter "name=katello" --format "{{.Names}}" 2>/dev/null | wc -l | tr -d ' ')
[[ "${_KATELLO_RUNNING}" -ge 1 ]] || \
    die "docker compose up -d returned 0 but no katello containers are running.
    Diagnose: docker-compose -f ${COMPOSE_FILE} logs
    Then retry: sudo bash scripts/enroll.sh"
info "Containers started (${_KATELLO_RUNNING} katello container(s) running). Waiting for foreman-installer (10-15 min)..."
info "Follow: docker-compose -f ${COMPOSE_FILE} logs -f foreman-katello"

MAX_WAIT="${FOREMAN_WAIT_TIMEOUT:-1800}"; ELAPSED=0; INTERVAL=15
while ! docker exec katello-foreman test -f /var/lib/foreman/.sourceos-initialized 2>/dev/null; do
    sleep $INTERVAL; ELAPSED=$((ELAPSED + INTERVAL))
    # Detect container crash immediately — without this, a crashed container causes
    # `docker exec ... 2>/dev/null` to silently exit non-zero and the loop counts up
    # to MAX_WAIT (30 min) before dying with a misleading "installer is slow" message.
    if ! docker ps --filter "name=katello-foreman" --filter "status=running" \
            --format "{{.Names}}" 2>/dev/null | grep -q katello-foreman; then
        die "katello-foreman container stopped unexpectedly during install.
    Logs:    docker-compose -f ${COMPOSE_FILE} logs --tail=50 katello-foreman
    Restart: docker-compose -f ${COMPOSE_FILE} up -d && sudo bash scripts/enroll.sh"
    fi
    if [[ $ELAPSED -ge $MAX_WAIT ]]; then
        echo
        warn "Foreman installer still running after ${MAX_WAIT}s."
        warn "Options:"
        warn "  Watch:   docker exec katello-foreman tail -f /var/log/foreman-installer/foreman-installer.log"
        warn "  Restart: docker-compose -f ${COMPOSE_FILE} restart foreman-katello"
        warn "  Re-run:  bash scripts/enroll.sh  (will skip Foreman if already complete)"
        die  "Timed out. Increase timeout: FOREMAN_WAIT_TIMEOUT=3600 bash scripts/enroll.sh"
    fi
    [[ $((ELAPSED % 30)) -eq 0 ]] && info "  foreman-installer running (${ELAPSED}s / ${MAX_WAIT}s)..."
done

wait_for_url "${KATELLO_URL}/api/v2/status" "Foreman API" 120
ok "Foreman+Katello ready ($(elapsed))"

# ── Step 5: Katello content structure ─────────────────────────────────────────

step 5 "Katello content structure"

FOREMAN_URL="${KATELLO_URL}" FOREMAN_USER="${KATELLO_USER}" \
FOREMAN_PASSWORD="${KATELLO_PASSWORD}" ORG="${ORG}" \
bash "${REPO_ROOT}/scripts/katello-sourceos-setup.sh"

ok "Org, product, repos, content view ready ($(elapsed))"

# ── Step 6: SOPS-encrypted secrets ───────────────────────────────────────────

step 6 "Encrypt secrets with SOPS"

require_cmd sops

_needs_encrypt=0
if [[ -f "${SECRETS_YAML}" ]]; then
    # grep for the sops metadata top-level key rather than a python substring
    # search — a YAML comment containing the word 'sops' would fool the old check.
    if grep -q '^sops:' "${SECRETS_YAML}" 2>/dev/null; then
        ok "secrets.yaml already SOPS-encrypted"
    else
        warn "secrets.yaml exists but is not encrypted — re-encrypting"
        _needs_encrypt=1
    fi
else
    _needs_encrypt=1
fi

if [[ "${_needs_encrypt}" -eq 1 ]]; then
    PLAINTEXT=$(mktemp /tmp/sourceos-secrets-XXXXXX.yaml)
    trap "rm -f ${PLAINTEXT}" EXIT
    printf 'katello-password: "%s"\n' "${KATELLO_PASSWORD}" > "${PLAINTEXT}"
    # Write to a temp file on the same filesystem so the final mv is atomic.
    # A plain `> ${SECRETS_YAML}` would truncate the file before sops runs;
    # if sops then fails the file is empty and subsequent re-runs skip encryption.
    _SECRETS_TMP=$(mktemp "${SOURCEOS_DIR}/secrets-XXXXXX.yaml.tmp")
    chmod 600 "${_SECRETS_TMP}"
    trap "rm -f ${PLAINTEXT} ${_SECRETS_TMP}" EXIT
    SOPS_AGE_RECIPIENTS="${AGE_PUBKEY}" sops --encrypt "${PLAINTEXT}" > "${_SECRETS_TMP}"
    [[ -s "${_SECRETS_TMP}" ]] || \
        die "sops --encrypt produced empty output — check AGE_PUBKEY format and sops version"
    mv "${_SECRETS_TMP}" "${SECRETS_YAML}"
    # mv preserves permissions from _SECRETS_TMP (already 600 via umask 077).
    rm -f "${PLAINTEXT}"; trap - EXIT
    ok "Encrypted secrets written to ${SECRETS_YAML} ($(elapsed))"
fi

# ── Step 7: harmonia binary cache signing key ─────────────────────────────────

step 7 "harmonia binary cache signing key"

if [[ -f "${HARMONIA_KEY}" && -f "${HARMONIA_PUB}" ]]; then
    ok "harmonia signing key already exists"
elif [[ -f "${HARMONIA_KEY}" || -f "${HARMONIA_PUB}" ]]; then
    # Partial state: one file exists but not the other. Regenerating would produce
    # a new key that orphans any packages signed with the old key. Fail loudly.
    die "Partial harmonia key state detected (one of key/pub missing).
    Delete both and re-run:
      rm -f ${HARMONIA_KEY} ${HARMONIA_PUB}
      sudo bash scripts/enroll.sh"
else
    # nix-store --generate-binary-cache-key <name> <secret-key-file> <public-key-file>
    nix-store --generate-binary-cache-key "builder-aarch64-1" "${HARMONIA_KEY}" "${HARMONIA_PUB}"
    [[ -s "${HARMONIA_KEY}" && -s "${HARMONIA_PUB}" ]] || \
        die "nix-store --generate-binary-cache-key produced empty key file(s)
        Remove and re-run: rm -f ${HARMONIA_KEY} ${HARMONIA_PUB} && sudo bash scripts/enroll.sh"
    chmod 600 "${HARMONIA_KEY}"
    ok "Generated harmonia signing key ($(elapsed))"
fi

HARMONIA_PUBKEY=$(cat "${HARMONIA_PUB}")
[[ -n "${HARMONIA_PUBKEY}" ]] || \
    die "harmonia public key file is empty or malformed: ${HARMONIA_PUB}
    Delete both and re-run: rm -f ${HARMONIA_KEY} ${HARMONIA_PUB} && sudo bash scripts/enroll.sh"
info "harmonia public key: ${HARMONIA_PUBKEY}"

# ── Step 8: minisign key pair + nix-cache-info signature ──────────────────────

step 8 "minisign key pair and nix-cache-info signature"

rm -f "${MINISIGN_CACHE_INFO}.tmp"  # clean up stale temp from a previous interrupted run
require_cmd minisign

if [[ -f "${MINISIGN_PUB}" && -f "${MINISIGN_SEC}" ]]; then
    ok "minisign key pair already exists"
elif [[ -f "${MINISIGN_PUB}" || -f "${MINISIGN_SEC}" ]]; then
    die "Partial minisign key state detected (one of pub/sec missing).
    Delete both and re-run:
      rm -f ${MINISIGN_PUB} ${MINISIGN_SEC}
      sudo bash scripts/enroll.sh"
else
    info "Generating minisign key pair (no passphrase — press Enter twice if prompted)..."
    minisign -G -p "${MINISIGN_PUB}" -s "${MINISIGN_SEC}" -W
    chmod 600 "${MINISIGN_SEC}"
    ok "Generated ${MINISIGN_PUB} ($(elapsed))"
fi

# `grep -v` exits 1 when every line matches the pattern (e.g. file has only
# the comment line). With set -o pipefail that propagates into the $() and fires
# set -e before the empty guard below can print a useful message. `|| true`
# lets the guard handle the empty-string case with a clear diagnostic.
SIGNING_PUBKEY=$(grep -v '^untrusted comment' "${MINISIGN_PUB}" 2>/dev/null | head -1 || true)
[[ -n "${SIGNING_PUBKEY}" ]] || \
    die "minisign public key file is empty or malformed: ${MINISIGN_PUB}
    Delete and re-run: rm -f ${MINISIGN_PUB} ${MINISIGN_SEC} && sudo bash scripts/enroll.sh"
info "Signing public key: ${SIGNING_PUBKEY}"

# Write nix-cache-info atomically then sign it. nginx serves the .minisig file
# alongside harmonia so sourceos-syncd can verify the cache before pulling.
cat > "${MINISIGN_CACHE_INFO}.tmp" <<EOF
StoreDir: /nix/store
WantMassQuery: 1
Priority: 30
EOF
# Priority 30 < 40 (cache.nixos.org default) — lower number = higher priority.
# This ensures nix prefers the local harmonia cache over the remote when both
# are configured as substituters.
mv "${MINISIGN_CACHE_INFO}.tmp" "${MINISIGN_CACHE_INFO}"

minisign -S -s "${MINISIGN_SEC}" -m "${MINISIGN_CACHE_INFO}" -x "${MINISIGN_CACHE_INFO_SIG}" \
    || die "minisign signing failed. Possible causes:
    - ${MINISIGN_SEC} has a passphrase (should be empty; generated with -W)
    - ${MINISIGN_SEC} is corrupt or unreadable (check permissions/size)
    - Disk full on ${SOURCEOS_DIR}
    Diagnose: minisign -S -s ${MINISIGN_SEC} -m ${MINISIGN_CACHE_INFO} -x ${MINISIGN_CACHE_INFO_SIG}"
[[ -s "${MINISIGN_CACHE_INFO_SIG}" ]] || \
    die "minisign exited 0 but produced an empty signature file: ${MINISIGN_CACHE_INFO_SIG}"
ok "Signed nix-cache-info → ${MINISIGN_CACHE_INFO_SIG} ($(elapsed))"

# ── Step 9: Write enroll.nix (replaces old sed-patching approach) ─────────────

step 9 "Write enroll.nix (device-specific NixOS settings)"

rm -f "${ENROLL_NIX}.tmp"  # clean up stale temp from a previous interrupted run
write_enroll_nix "${SIGNING_PUBKEY}" "${HARMONIA_PUBKEY}"
ok "enroll.nix written — no Nix file patching needed ($(elapsed))"

# ── Step 10: Build + push NixOS closure to local cache ────────────────────────

step 10 "Build NixOS closure + push to harmonia cache"

info "Building builder-aarch64 system closure..."
BUILD_LOG="/tmp/sourceos-enroll-nix-build-$(date +%s).log"
info "Build log: ${BUILD_LOG}  (tail -f ${BUILD_LOG} in another terminal to follow)"
# head -1 guards against multi-output derivations: --print-out-paths prints one
# path per output; command substitution would embed a newline making -e fail.
# set +e/set -e mirrors the nixos-rebuild pattern: with set -euo pipefail,
# var=$(failing_pipeline) fires set -e before the guard below can print BUILD_LOG.
set +e
CLOSURE=$(nix build "${REPO_ROOT}#nixosConfigurations.${HOST}.config.system.build.toplevel" \
    --no-link --print-out-paths 2>"${BUILD_LOG}" | head -1)
NIX_BUILD_EXIT=${PIPESTATUS[0]}
set -e
[[ $NIX_BUILD_EXIT -eq 0 ]] || die "nix build failed (exit ${NIX_BUILD_EXIT}). Build log: ${BUILD_LOG}
    For full trace: nix build ${REPO_ROOT}#nixosConfigurations.${HOST}.config.system.build.toplevel --no-link --show-trace"
# nix build emits errors only to stderr (captured to BUILD_LOG above).
# Verify stdout produced a non-empty, existing store path.
[[ -n "${CLOSURE}" && -e "${CLOSURE}" ]] || \
    die "nix build exited 0 but produced no valid store path — unexpected; check: ${BUILD_LOG}"
ok "Built: ${CLOSURE}"

# Harmonia must be running before we can push (it starts after pass-2 rebuild).
# We push after pass-2. Skip here and record for the next step.
info "Closure push to harmonia will happen after pass-2 rebuild in step 11."

# ── Step 11: nixos-rebuild pass 2 (live config with all secrets + keys) ───────

step 11 "nixos-rebuild switch — pass 2 (live config: secrets, signing key, harmonia)"

info "Activating final configuration..."
PASS2_LOG="/tmp/sourceos-enroll-pass2-$(date +%s).log"
set +e
nixos-rebuild switch --flake "${REPO_ROOT}#${HOST}" --impure 2>&1 | \
    tee "${PASS2_LOG}" | \
    grep --line-buffered -E '(building|fetching|error|warning|Error|FAILED|activating)'
NB2_EXIT=${PIPESTATUS[0]}
set -e
[[ $NB2_EXIT -eq 0 ]] || die "Pass 2 rebuild failed (exit ${NB2_EXIT}). Full log: ${PASS2_LOG}
    Check: journalctl -xe | tail -50
    The previous generation (pass 1) is still bootable via the systemd-boot menu."
ok "Pass 2 complete ($(elapsed)) — log: ${PASS2_LOG}"

# Confirm the activated generation matches the closure we built in step 10.
CURRENT_GEN=$(readlink /run/current-system 2>/dev/null || echo "")
if [[ -z "${CURRENT_GEN}" ]]; then
    warn "/run/current-system not readable — pass-2 activation may have failed"
    warn "  Check: nixos-rebuild list-generations"
elif [[ "${CURRENT_GEN}" == "${CLOSURE}" ]]; then
    ok "Active generation matches built closure"
else
    info "Active generation: ${CURRENT_GEN}"
    info "Built closure:     ${CLOSURE}"
    warn "Active generation differs from step-10 closure — check: nixos-rebuild list-generations"
fi

# Now push the closure to the running harmonia cache.
# Wait up to 60s for harmonia (it starts during pass-2 activation); this is
# warn-only — a push failure does not block enrollment. sourceos-syncd will
# repopulate the cache on its first sync cycle.
info "Pushing NixOS closure to local harmonia cache (http://127.0.0.1:8101)..."
_HARM_UP=0
for _i in {1..12}; do
    if curl -fsSk --max-time 5 "http://127.0.0.1:8101/nix-cache-info" &>/dev/null; then
        _HARM_UP=1; break
    fi
    sleep 5
done
if [[ $_HARM_UP -eq 1 ]]; then
    # Push the active system (CURRENT_GEN) first — it may differ from CLOSURE if
    # nixos-rebuild fetched a cached derivation with a different hash. Without this,
    # the running system would not be in harmonia after enrollment.
    if [[ -n "${CURRENT_GEN}" && "${CURRENT_GEN}" != "${CLOSURE}" ]]; then
        if nix copy --to "http://127.0.0.1:8101?compression=zstd" "${CURRENT_GEN}"; then
            ok "Active system pushed to harmonia cache"
        else
            warn "nix copy (active gen) failed — run: nix copy --to 'http://127.0.0.1:8101?compression=zstd' ${CURRENT_GEN}"
        fi
    fi
    if nix copy --to "http://127.0.0.1:8101?compression=zstd" "${CLOSURE}"; then
        ok "Step-10 closure pushed to harmonia cache"
    else
        warn "nix copy failed — run manually: nix copy --to 'http://127.0.0.1:8101?compression=zstd' ${CLOSURE}"
    fi
else
    warn "harmonia not responding on :8101 after 60s — push manually after it starts"
    warn "  nix copy --to 'http://127.0.0.1:8101?compression=zstd' ${CURRENT_GEN:-${CLOSURE}}"
fi

# Promote content view to stable so sourceos-syncd can pick it up
info "Promoting content view to stable..."

# Verify katello-foreman is still running before hammer calls — a stopped
# container causes docker exec to exit 1 which 2>/dev/null silently swallows,
# making promotion failures look like "already promoted".
if ! docker ps --filter "name=katello-foreman" --format "{{.Names}}" 2>/dev/null | grep -q katello-foreman; then
    warn "katello-foreman container is not running — skipping CV promotion"
    warn "  Start: docker-compose -f ${COMPOSE_FILE} up -d"
    warn "  Then promote manually: bash scripts/promote.sh"
else
    CV_VERSION=$(docker exec katello-foreman hammer \
        --server "${KATELLO_URL}" --username "${KATELLO_USER}" --password "${KATELLO_PASSWORD}" \
        --output json content-view version list \
        --organization "${ORG}" --content-view "sourceos-builder-aarch64" 2>/dev/null | \
        python3 -c "import json,sys; vs=json.load(sys.stdin); print(sorted(vs,key=lambda v:v['ID'])[-1]['Version'])" \
        2>/dev/null || echo "")

    if [[ -n "${CV_VERSION}" ]]; then
        for _promote_env in candidate stable; do
            if docker exec katello-foreman hammer \
                    --server "${KATELLO_URL}" --username "${KATELLO_USER}" --password "${KATELLO_PASSWORD}" \
                    content-view version promote \
                    --organization "${ORG}" \
                    --content-view "sourceos-builder-aarch64" \
                    --version "${CV_VERSION}" \
                    --to-lifecycle-environment "${_promote_env}" 2>/dev/null; then
                ok "Promoted to ${_promote_env}"
            else
                info "Already at ${_promote_env} (or skipping)"
            fi
        done
    else
        warn "Could not determine CV version — promote manually after Katello sync completes"
    fi
fi

# ── Step 12: Verify ────────────────────────────────────────────────────────────

step 12 "Verify enrollment"

# Poll for sourceos-syncd to become active (up to 30s) rather than a blind sleep.
# On a fast path (cached build) the service may be active within seconds; on a
# slow path it can take longer. A fixed sleep either wastes time or races.
HEALTHY=1
_SYNCD_UP=0
for _i in {1..6}; do
    if systemctl is-active --quiet sourceos-syncd 2>/dev/null; then
        _SYNCD_UP=1; break
    fi
    sleep 5
done
if [[ $_SYNCD_UP -eq 1 ]]; then
    ok "sourceos-syncd: active"
else
    warn "sourceos-syncd not active after 30s (may still be starting)"
    HEALTHY=0
fi

# Check sops-nix activation by testing for the decrypted secret file rather
# than by service state alone. `is-failed` exits 1 (not-failed) if the unit
# doesn't exist, producing a false "ok" even when sops-nix isn't configured.
# The actual secret path is the ground truth.
_SOPS_SECRET="/run/secrets/katello-password"
if systemctl is-failed --quiet sops-nix-activate 2>/dev/null; then
    warn "sops-nix-activate FAILED — secrets not decrypted; sourceos-syncd will not start"
    warn "  Diagnose: journalctl -u sops-nix-activate | tail -30"
    warn "  Common cause: age key mismatch — re-run: rm -f ${SECRETS_YAML} && sudo bash scripts/enroll.sh"
    HEALTHY=0
elif [[ -f "${_SOPS_SECRET}" ]]; then
    ok "sops-nix-activate: ok — secret present at ${_SOPS_SECRET}"
else
    warn "sops-nix-activate: secret not at ${_SOPS_SECRET} — may still be activating"
    warn "  Diagnose: journalctl -u sops-nix-activate | tail -20"
    HEALTHY=0
fi

# Verify Katello containers are still running after the long enrollment.
# They can be OOM-killed during nix build (steps 10–11) without the script noticing.
_KATELLO_FINAL=$(docker ps --filter "name=katello" --format "{{.Names}}" 2>/dev/null | wc -l | tr -d ' ')
if [[ "${_KATELLO_FINAL}" -ge 1 ]]; then
    ok "Katello containers: ${_KATELLO_FINAL} running"
else
    warn "No Katello containers running — they may have crashed during enrollment"
    warn "  Restart: docker-compose -f ${COMPOSE_FILE} up -d"
    HEALTHY=0
fi

if systemctl is-active --quiet harmonia 2>/dev/null; then
    ok "harmonia: active"
else
    warn "harmonia not active yet"
    warn "  Diagnose: journalctl -u harmonia | tail -20"
    warn "  Start:    systemctl start harmonia"
    HEALTHY=0
fi

if systemctl is-active --quiet nginx 2>/dev/null; then
    ok "nginx (nix-cache proxy): active"
    if curl -fsSk http://127.0.0.1:8101/nix-cache-info &>/dev/null; then
        ok "Nix cache at http://127.0.0.1:8101 responding"
    else
        warn "Nix cache at http://127.0.0.1:8101 not responding — is harmonia running?"
        warn "  Check: systemctl status harmonia"
        HEALTHY=0
    fi
    # Cryptographically verify the minisig, not just that the endpoint responds.
    # A stale or wrong-key sig would pass an existence check but fail here.
    _SIG_TMP=$(mktemp /tmp/nix-cache-info-XXXXX.minisig)
    # Trap ensures cleanup even if set -e fires inside this block.
    trap "rm -f ${_SIG_TMP}" EXIT
    if curl -fsSk http://127.0.0.1:8101/nix-cache-info.minisig -o "${_SIG_TMP}" 2>/dev/null && \
       [[ -s "${_SIG_TMP}" ]]; then
        if minisign -V -p "${MINISIGN_PUB}" -m "${MINISIGN_CACHE_INFO}" -x "${_SIG_TMP}" &>/dev/null; then
            ok "nix-cache-info minisig: signature valid"
        else
            warn "minisig served but signature is INVALID — re-sign:"
            warn "  minisign -S -s ${MINISIGN_SEC} -m ${MINISIGN_CACHE_INFO} -x ${MINISIGN_CACHE_INFO_SIG}"
            HEALTHY=0
        fi
    else
        warn "minisig not yet at /nix-cache-info.minisig — check nginx + ${MINISIGN_CACHE_INFO_SIG}"
        HEALTHY=0
    fi
    rm -f "${_SIG_TMP}"; trap - EXIT
else
    warn "nginx (nix-cache proxy): not active — minisig verification skipped"
    warn "  Diagnose: journalctl -u nginx | tail -20"
    warn "  Start:    systemctl start nginx"
    HEALTHY=0
fi

if [[ $HEALTHY -eq 1 ]]; then
    ok "All services healthy ($(elapsed))"
else
    warn "Some services not yet active. Run: sudo bash scripts/doctor.sh"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

banner
